Alex/rust crypto
banyancomputer/tomb-crypt pull request #10
Opened 2023-09-29 19:43 UTC by amiller68

- implements current interface using rust/crypto
- uses AES-GCM instead of AES-KW for protecting key material (compatibility change)

Starting PR for review but should be noted that on my system, wasm tests generate:

```
---- tomb_crypt::key_seal::tests::wasm_tests::api_token output ----
    error output:
        panicked at library/std/src/sys/wasm/../unsupported/time.rs:31:9:
        time not implemented on this platform
```

2023-09-29 19:52 UTC, organizedgrime commented on src/key_seal/ec_public_encryption_key.rs
> +// use async_trait::async_trait;
why are we leaving commented code in?

2023-09-29 19:54 UTC, organizedgrime commented on src/key_seal/error.rs
> +            // InvalidBase64(err) => Some(err),
should these be commented?

2023-09-29 19:55 UTC, organizedgrime requested changes
looks good in general just tidy up comments and we should merge

2023-10-02 13:29 UTC, amiller68 commented
Still for some reason:
this
```
pub fn new(audience: String, subject: String) -> Self {
        Self(
            Claims::create(Duration::from_secs(JWT_DURATION))
                .with_audience(audience)
                .with_subject(subject)
                .with_nonce(
                    rand::thread_rng()
                        .sample_iter(&Alphanumeric)
                        .take(16)
                        .map(char::from)
                        .collect::<String>(),
                ),
        )
    }
    ```
    generates
    
```
console.log div contained:
    panicked at library/std/src/sys/wasm/../unsupported/time.rs:31:9:
    time not implemented on this platform
    ```

2023-10-02 18:54 UTC, amiller68 commented on src/key_seal/ec_encryption_key.rs
> +    async fn fingerprint(&self) -> Result<Arc<[u8; FINGERPRINT_SIZE]>, TombCryptError> {
We definitely dont want this

2023-10-05 13:43 UTC, sstelfox requested changes
Whoops didn't finish submitting this review

2023-10-05 13:43 UTC, sstelfox commented on Cargo.toml
> +chrono = "0.4.22"
For our dependencies we want to keep them a bit more unconstrained than this. It should be tied to the latest stable version according to semver semantics. So > 1.0.0 it should be pinned to the major revision < 1.0.0 it should be pinned to the latest minor version (2.3.4 would be ^2, 0.16.7 would be ^0.16)

2023-10-06 14:16 UTC, sstelfox requested changes

2023-10-06 14:16 UTC, sstelfox commented on src/key_seal.rs
> +    // }
We don't want to leave dead code behind. We can always go back into the version history if we need this.

2023-10-06 14:16 UTC, sstelfox commented on src/key_seal.rs
>      ];
@organizedgrime was having compatibility issues with the sec1 format of bytes. I don't think those are consistently compatible with what we're using (unrelated to the key wrapping breakage).

2023-10-06 14:16 UTC, sstelfox commented on src/key_seal/internal.rs
> +// }
Don't need to leave dead code behind

2023-10-06 19:26 UTC, organizedgrime commented on src/key_seal/common.rs
> +        public_key.fingerprint().await
not sure this can be changed back. doing so incurrs compiler complaints about the ability to send data between threads safely, that's the only reason this is as is anyway. only seems to be a problem introduced by the Send stuff

2023-10-11 14:19 UTC, sstelfox approved these changes

2023-10-11 14:52 UTC, merged